# -manager=10.0.2.10:39311
./bin/linux_amd64/syz-fuzzer -executor=./bin/linux_amd64/syz-executor \
    -name=vm-0 \
    -arch=amd64 \
    -sandbox=none \
    -procs=1 \
    -v=100 \
    -cover=false \
    -debug=false \
    -test=false \
    -runtest=false \
    -output=stdout \
    -config=./my.cfg 
